#ifndef __MS5611_INSTANCE_H
#define __MS5611_INSTANCE_H

#include "system_barometer_if.h"

SystemDeviceResult Ms5611I2cBarometerInstance_Init(uint8_t instance);
SystemDeviceResult Ms5611I2cBarometerInstance_Start(uint8_t instance);
SystemDeviceResult Ms5611I2cBarometerInstance_Stop(uint8_t instance);
SystemDeviceResult Ms5611I2cBarometerInstance_Process(uint8_t instance);
SystemDeviceResult Ms5611I2cBarometerInstance_InfoGet(uint8_t instance, SystemDeviceInfo *info);
SystemDeviceResult Ms5611I2cBarometerInstance_CapabilitiesGet(uint8_t instance, uint32_t *mask);
SystemDeviceResult Ms5611I2cBarometerInstance_HealthGet(uint8_t instance, SystemDeviceHealth *health);
SystemDeviceResult Ms5611I2cBarometerInstance_LatestSampleGet(uint8_t instance, SystemBarometerSample *sample);
SystemDeviceResult Ms5611I2cBarometerInstance_SelfTestRun(uint8_t instance, SystemDeviceSelfTestResult *result);
SystemDeviceResult Ms5611I2cBarometerInstance_ConfigApply(uint8_t instance, const SystemBarometerConfig *config, SystemDeviceConfigReport *report);
SystemDeviceResult Ms5611I2cBarometerInstance_ConfigVerify(uint8_t instance, const SystemBarometerConfig *config, SystemDeviceConfigReport *report);
SystemDeviceResult Ms5611I2cBarometerInstance_EffectiveConfigGet(uint8_t instance, SystemBarometerConfig *config);
SystemDeviceResult Ms5611I2cBarometerInstance_NoiseCharacteristicsGet(uint8_t instance, SystemBarometerNoiseCharacteristics *noise);
SystemDeviceResult Ms5611SpiBarometerInstance_Init(uint8_t instance);
SystemDeviceResult Ms5611SpiBarometerInstance_Start(uint8_t instance);
SystemDeviceResult Ms5611SpiBarometerInstance_Stop(uint8_t instance);
SystemDeviceResult Ms5611SpiBarometerInstance_Process(uint8_t instance);
SystemDeviceResult Ms5611SpiBarometerInstance_InfoGet(uint8_t instance, SystemDeviceInfo *info);
SystemDeviceResult Ms5611SpiBarometerInstance_CapabilitiesGet(uint8_t instance, uint32_t *mask);
SystemDeviceResult Ms5611SpiBarometerInstance_HealthGet(uint8_t instance, SystemDeviceHealth *health);
SystemDeviceResult Ms5611SpiBarometerInstance_LatestSampleGet(uint8_t instance, SystemBarometerSample *sample);
SystemDeviceResult Ms5611SpiBarometerInstance_SelfTestRun(uint8_t instance, SystemDeviceSelfTestResult *result);
SystemDeviceResult Ms5611SpiBarometerInstance_ConfigApply(uint8_t instance, const SystemBarometerConfig *config, SystemDeviceConfigReport *report);
SystemDeviceResult Ms5611SpiBarometerInstance_ConfigVerify(uint8_t instance, const SystemBarometerConfig *config, SystemDeviceConfigReport *report);
SystemDeviceResult Ms5611SpiBarometerInstance_EffectiveConfigGet(uint8_t instance, SystemBarometerConfig *config);
SystemDeviceResult Ms5611SpiBarometerInstance_NoiseCharacteristicsGet(uint8_t instance, SystemBarometerNoiseCharacteristics *noise);

#endif /* __MS5611_INSTANCE_H */
